# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5c9c08fa9ec81739ba9902ea32aad0620d420d99dddf3e67a43d5174c3f255a51960a94b5d003e9cb1ba2955432f23e539e59ce871f41a445d2246b66f51df4

test:
  secret_key_base: dfdc241b31a583b4454c8959a04ec0b2c60495ac67f64cd76b8d8d22fe95f8a7ea461cf7c6f6075b56966868f89a6e00079278e4ee74627d19daa2bb3f8094de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
